# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js as the base image
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the source code
COPY src ./src
COPY tsconfig.json ./

# Build the TypeScript code
RUN npm run build

# Use a minimal Node.js runtime for the release image
FROM node:18-alpine AS release

# Set the working directory
WORKDIR /app

# Copy the build artifacts from the builder stage
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./

# Install only production dependencies
RUN npm install --only=production

# Command to run the application
ENTRYPOINT ["node", "dist/index.cjs"]

# Environment variables can be set at runtime
# ENV GOOGLE_CALENDAR_ID=your_calendar_id
# ENV GOOGLE_TIME_ZONE=your_time_zone
# ENV GOOGLE_CREDENTIALS_PATH=your_credentials_path
